services:
  conversor:
    build:
      context: ./conversor/conversor
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_URL: "jdbc:postgresql://local-postgres-compose:5432/vertical_logistica_database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "jMZDNzN1D7gp7Qk"
    expose:
      - "8080"
    depends_on:
      - local-postgres-compose
    networks:
      - app-network
  local-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "jMZDNzN1D7gp7Qk"
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge


