services:
  conversor:
    build:
      context: ./conversor/conversor
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_URL: "jdbc:postgresql://postgresql:5432/vertical_logistica_database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "jMZDNzN1D7gp7Qk"
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      - app-network
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "jMZDNzN1D7gp7Qk"
      POSTGRES_DB: "vertical_logistica_database"
    ports:
      - "5432:5432"
    volumes:
      - database-postgres:/var/lib/postgresql/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  database-postgres: